# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41530d06add97e260fb910293346ed99624ff96ea4f61266a02cdeed2b9a4bacb246aeadf9526ee242cd2d613a0eceeb4f9ce52e192a168d4ca4ad3f0e7f04f

test:
  secret_key_base: a98c3bef0695b02a48a00438f0a9f8e13e383f3ee0d3576b7588b195ff22cab39228cb8a73724ec0b54055509bc99493c8454191fd31359d8687682f8bad0332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
